### PR TITLE
tweaks

### PR DESCRIPTION
**Pull request by matthdsm**
- bump travis ubuntu version
- update dockerfiles
- lint yaml files 
- remove py3 env (atropos) since py3 is now default

hopefully, this also fixes the build issues. 
The image source is now debian-slim, which should help keeping the image size down

### CODE REVIEW

**Comment by roryk** [comment]
Thank you so much!

**Comment by matthdsm** [comment]
Build failed, but it seems like the conda resolvement is the major issue here.

Could you explain the though process behind the setup? Because there's stated to different images are there to break up the monolithic image, but as far as I can see, the base image is a complete install?

A possible solution here would be to extrapolate which steps require which packages, and go from there. Also the amount of different env's dramatically increase the build time..

**Comment by matthdsm** [comment]
I would suggest changing the `bcbio-base` image from a complete install to a true "base" image.
i.e. all build dependencies and only the bcbio codebase.

All child images can then install their own dependencies based on the different yaml files.

Let me know what you think.
Cheers
M

**Comment by matthdsm** [comment]
note, the comment above would require a `--notools` flag, so conda and bcbio is installed as usual, but skips all the tool installation steps.

M

**Pull request merged**
